# Generated by Django 4.2.28 on 2026-02-03 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='principal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Principal',
                'verbose_name_plural': 'Principals',
                'db_table': 'principals',
                'ordering': ['registration_id'],
                'indexes': [models.Index(fields=['registration_id'], name='principals_registr_31019b_idx')],
            },
        ),
    ]
