# Generated by Django 4.2.28 on 2026-02-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
